dist: xenial
language: python
python:
    - "3.7"

before_install:
    - sudo add-apt-repository ppa:deadsnakes/ppa -y
    - sudo apt-get update
    - sudo apt-get install python3.6
    - sudo apt-get install openssl
    - openssl enc -aes-256-cbc -md sha256 -d -in auth.enc -out auth.json -k $DECRYPT_PASS

install:
    - pip install -r requirements.txt
    - pip install nox

script:
    - nox
