name: Ping Instance

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: read
  id-token: write # required for secret manager

jobs:
  ping_instance:
    name: Ping Instance
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ vars.GOOGLE_CLOUD_PROJECT }}
      IP_ADDRESS: ${{ vars.IP_ADDRESS }} # Required IP address
      DATABASE_PORT: 3306 # Or your database port

    steps:
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935 # v2.1.8
        with:
          workload_identity_provider: ${{ vars.PROVIDER_NAME }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
          access_token_lifetime: 600s

      - id: secrets
        name: Get secrets
        uses: google-github-actions/get-secretmanager-secrets@a8440875e1c2892062aef9061228d4f1af8f919b # v2.2.3
        with:
          secrets: |-
            MYSQL_CONNECTION_NAME:${{ vars.GOOGLE_CLOUD_PROJECT }}/MYSQL_CONNECTION_NAME

      - name: Download Cloud SQL Proxy
        run: |
          wget -O cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.13.0/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy

      - name: Ping Instance
        run: |
          ./cloud-sql-proxy "${{ steps.secrets.outputs.MYSQL_CONNECTION_NAME }}" --port "${{ env.DATABASE_PORT }}" &
          sleep 5
          nc -zv "${{ env.IP_ADDRESS }}" "${{ env.DATABASE_PORT }}"
          if [ $? -eq 0 ]; then
            echo "Successfully pinged the instance!"
          else
            echo "Failed to ping the instance."
            exit 1
          fi