# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from google.cloud.sql.connector.proto import (
    sql_data_service_pb2 as google_dot_cloud_dot_sql_dot_connector_dot_proto_dot_sql__data__service__pb2,
)

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in google/cloud/sql/connector/proto/sql_data_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SqlDataServiceStub:
    """Service for streaming data to and from Cloud SQL instances.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSqlData = channel.stream_stream(
                '/google.cloud.sql.v1beta4.SqlDataService/StreamSqlData',
                request_serializer=google_dot_cloud_dot_sql_dot_connector_dot_proto_dot_sql__data__service__pb2.StreamSqlDataRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_sql_dot_connector_dot_proto_dot_sql__data__service__pb2.StreamSqlDataResponse.FromString,
                _registered_method=True)


class SqlDataServiceServicer:
    """Service for streaming data to and from Cloud SQL instances.
    """

    def StreamSqlData(self, request_iterator, context):
        """`StreamSqlData` establishes a bidirectional stream to a Cloud SQL instance,
        and then streams data to and from the instance.

        The first message from the client MUST be a `StreamSqlDataRequest` request
        with configuration settings, including required values for the
        `connection_settings` field. Subsequent messages from the client may
        contain the `payload` field.

        Messages from the server may contain the `payload` field.

        The `payload` fields of the request and response streams contain the raw
        data of the database's native wire protocol (e.g., PostgreSQL wire
        protocol). The database client is responsible for generating and parsing
        this data.

        Any errors on initial connection (e.g., connection failure, authorization
        issues, network problems) will result in the stream being terminated with
        an appropriate RPC status exception.

        After a successful connection is made, if an error occurs, then the server
        terminates connection and returns the appropriate RPC status exception.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SqlDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSqlData': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSqlData,
                    request_deserializer=google_dot_cloud_dot_sql_dot_connector_dot_proto_dot_sql__data__service__pb2.StreamSqlDataRequest.FromString,
                    response_serializer=google_dot_cloud_dot_sql_dot_connector_dot_proto_dot_sql__data__service__pb2.StreamSqlDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.cloud.sql.v1beta4.SqlDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('google.cloud.sql.v1beta4.SqlDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SqlDataService:
    """Service for streaming data to and from Cloud SQL instances.
    """

    @staticmethod
    def StreamSqlData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/google.cloud.sql.v1beta4.SqlDataService/StreamSqlData',
            google_dot_cloud_dot_sql_dot_connector_dot_proto_dot_sql__data__service__pb2.StreamSqlDataRequest.SerializeToString,
            google_dot_cloud_dot_sql_dot_connector_dot_proto_dot_sql__data__service__pb2.StreamSqlDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
