steps:
  - id: run-tests
    name: python:3.10
    entrypoint: nox
    args:
      - -s
      - "system-3.10"
    env:
      - 'MYSQL_CONNECTION_NAME=${MYSQL_CONNECTION_NAME}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_IAM_USER=${MYSQL_IAM_USER}'
      - 'MYSQL_PASS=${MYSQL_PASS}'
      - 'MYSQL_DB=${MYSQL_DB}'
      - 'POSTGRES_CONNECTION_NAME=${POSTGRES_CONNECTION_NAME}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_IAM_USER=${POSTGRES_IAM_USER}'
      - 'POSTGRES_PASS=${POSTGRES_PASS}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_CAS_CONNECTION_NAME=${POSTGRES_CAS_CONNECTION_NAME}'
      - 'POSTGRES_CAS_PASS=${POSTGRES_CAS_PASS}'
      - 'POSTGRES_CUSTOMER_CAS_CONNECTION_NAME=${POSTGRES_CUSTOMER_CAS_CONNECTION_NAME}'
      - 'POSTGRES_CUSTOMER_CAS_PASS=${POSTGRES_CUSTOMER_CAS_PASS}'
      - 'POSTGRES_CUSTOMER_CAS_PASS_VALID_DOMAIN_NAME=${POSTGRES_CUSTOMER_CAS_PASS_VALID_DOMAIN_NAME}'
      - 'SQLSERVER_CONNECTION_NAME=${SQLSERVER_CONNECTION_NAME}'
      - 'SQLSERVER_USER=${SQLSERVER_USER}'
      - 'SQLSERVER_PASS=${SQLSERVER_PASS}'
      - 'SQLSERVER_DB=${SQLSERVER_DB}'
availableSecrets:
  secretManager:
  - versionName: 'projects/$PROJECT_ID/secrets/MYSQL_CONNECTION_NAME/versions/latest'
    env: 'MYSQL_CONNECTION_NAME'
  - versionName: 'projects/$PROJECT_ID/secrets/MYSQL_USER/versions/latest'
    env: 'MYSQL_USER'
  - versionName: 'projects/$PROJECT_ID/secrets/MYSQL_USER_IAM_PYTHON/versions/latest'
    env: 'MYSQL_IAM_USER'
  - versionName: 'projects/$PROJECT_ID/secrets/MYSQL_PASS/versions/latest'
    env: 'MYSQL_PASS'
  - versionName: 'projects/$PROJECT_ID/secrets/MYSQL_DB/versions/latest'
    env: 'MYSQL_DB'
  - versionName: 'projects/$PROJECT_ID/secrets/POSTGRES_CONNECTION_NAME/versions/latest'
    env: 'POSTGRES_CONNECTION_NAME'
  - versionName: 'projects/$PROJECT_ID/secrets/POSTGRES_USER/versions/latest'
    env: 'POSTGRES_USER'
  - versionName: 'projects/$PROJECT_ID/secrets/POSTGRES_USER_IAM_PYTHON/versions/latest'
    env: 'POSTGRES_IAM_USER'
  - versionName: 'projects/$PROJECT_ID/secrets/POSTGRES_PASS/versions/latest'
    env: 'POSTGRES_PASS'
  - versionName: 'projects/$PROJECT_ID/secrets/POSTGRES_DB/versions/latest'
    env: 'POSTGRES_DB'
  - versionName: 'projects/$PROJECT_ID/secrets/POSTGRES_CAS_CONNECTION_NAME/versions/latest'
    env: 'POSTGRES_CAS_CONNECTION_NAME'
  - versionName: 'projects/$PROJECT_ID/secrets/POSTGRES_CAS_PASS/versions/latest'
    env: 'POSTGRES_CAS_PASS'
  - versionName: 'projects/$PROJECT_ID/secrets/POSTGRES_CUSTOMER_CAS_CONNECTION_NAME/versions/latest'
    env: 'POSTGRES_CUSTOMER_CAS_CONNECTION_NAME'
  - versionName: 'projects/$PROJECT_ID/secrets/POSTGRES_CUSTOMER_CAS_PASS/versions/latest'
    env: 'POSTGRES_CUSTOMER_CAS_PASS'
  - versionName: 'projects/$PROJECT_ID/secrets/POSTGRES_CUSTOMER_CAS_PASS_VALID_DOMAIN_NAME/versions/latest'
    env: 'POSTGRES_CUSTOMER_CAS_PASS_VALID_DOMAIN_NAME'
  - versionName: 'projects/$PROJECT_ID/secrets/SQLSERVER_CONNECTION_NAME/versions/latest'
    env: 'SQLSERVER_CONNECTION_NAME'
  - versionName: 'projects/$PROJECT_ID/secrets/SQLSERVER_USER/versions/latest'
    env: 'SQLSERVER_USER'
  - versionName: 'projects/$PROJECT_ID/secrets/SQLSERVER_PASS/versions/latest'
    env: 'SQLSERVER_PASS'
  - versionName: 'projects/$PROJECT_ID/secrets/SQLSERVER_DB/versions/latest'
    env: 'SQLSERVER_DB'
options:
  dynamicSubstitutions: true
  pool:
    name: ${_POOL_NAME}
  logging: CLOUD_LOGGING_ONLY
