 on:
   push:
     branches:
       - $default-branch
 name: release-please
 jobs:
   release-please:
     runs-on: ubuntu-latest
     steps:
       - uses: GoogleCloudPlatform/release-please-action@v2.26.0
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: python
           package-name: cloud-sql-python-connector